# Generated by Django 5.0.6 on 2024-07-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('eg', 'Electronic Gadjets'), ('ap', 'Apparels'), ('be', 'Beauty'), ('hd', 'Home Decor'), ('su', 'Subcriptions'), ('bo', 'Books'), ('co', 'Courses')], max_length=2)),
                ('detail', models.TextField(max_length=120)),
                ('image', models.ImageField(upload_to='affiliate_images/')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Goodies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='goodie_images/')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
