# Generated by Django 5.0.6 on 2024-07-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateproduct',
            name='category',
            field=models.CharField(choices=[('eg', 'Electronic Gadgets'), ('ap', 'Apparels'), ('be', 'Beauty'), ('hd', 'Home Decor'), ('su', 'Subscriptions'), ('bo', 'Books'), ('co', 'Courses')], max_length=2),
        ),
    ]
