# Generated by Django 5.0.6 on 2024-07-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_affiliateproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateproduct',
            name='detail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='affiliateproduct',
            name='image',
            field=models.ImageField(upload_to='affiliate_product/'),
        ),
        migrations.AlterField(
            model_name='goodies',
            name='image',
            field=models.ImageField(upload_to='goodies/'),
        ),
    ]
