# Generated by Django 5.0.6 on 2024-07-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_affiliateproduct_detail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goodies',
            new_name='Goodie',
        ),
    ]
