# Generated by Django 5.0.6 on 2024-07-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_affiliateproduct_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateproduct',
            name='category',
            field=models.CharField(choices=[('eg', 'Electronic Gadgets'), ('ap', 'Apparels'), ('hp', 'Health'), ('be', 'Beauty'), ('hd', 'Home Decor'), ('su', 'Subscriptions'), ('bo', 'Books'), ('co', 'Courses')], max_length=2),
        ),
        migrations.AlterField(
            model_name='affiliateproduct',
            name='name',
            field=models.TextField(default='Unknown Product Name', max_length=150),
        ),
        migrations.AlterField(
            model_name='goodie',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
