# Generated by Django 5.0.6 on 2024-07-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='overview',
            field=models.TextField(),
        ),
    ]
